### ISSUE TITLE
No module named 'vgn.utils'

### ISSUE THREAD

**Issue by midnightzz1** [PKU-EPIC/GraspNeRF#28]
When I run the scripts **bash run_simgrasp.sh**,its show like this
Blender 2.93.3 (hash 8b80d19f3641 built 2021-08-17 23:40:09)
Read prefs: /home/lzz/.config/blender/2.93/config/userpref.blend
Read blend: /home/lzz/GraspNeRF/./data/assets/material_lib_graspnet-v2.blend
########## Simulation Start ##########
Round 0
method: graspnerf
material_type: specular_and_transparent
views: [2, 6, 10, 14, 18, 22] 
######################################
[I] GraspNeRFPlanner: using ckpt: test
[I] GraspNeRFPlanner: load model at step 215000 of best metric 0.0032956636603921653
pybullet build time: May 25 2024 15:51:40
Traceback (most recent call last):
  File "/home/lzz/GraspNeRF/scripts/sim_grasp.py", line 124, in <module>
    main(args, round_idx, gpuid, render_frame_list)
  File "/home/lzz/GraspNeRF/scripts/sim_grasp.py", line 18, in main
    from gd.experiments import clutter_removal
  File "src/gd/experiments/clutter_removal.py", line 11, in <module>
    from gd.simulation import ClutterRemovalSim
  File "src/gd/simulation.py", line 9, in <module>
    from gd.utils import btsim, workspace_lines
  File "src/gd/utils/btsim.py", line 8, in <module>
    from vgn.utils.transform import Rotation, Transform
ModuleNotFoundError: No module named 'vgn.utils'
how to slove it?
my cuda is11.8 and  successfully installed the requirements

**Comment by tc-huang** [comment]
Hi, @midnightzz1,

I noticed that `Rotation` and `Transform` are available under the module `gd.utils.transform`. To solve the issue, I replaced the line of code from `from vgn.utils.transform import Rotation, Transform` to `from gd.utils.transform import Rotation, Transform`.

You can see the modified code in my forked repository at the following link: https://github.com/tc-huang/GraspNeRF/blob/e3e4ce62481eafccbf13112a7350fc1a7b418031/src/gd/utils/btsim.py#L9. I hope this helps you.

Best regards,
tc-huang

**Comment by midnightzz1** [comment]
thank you！I'll try that soon.
